[package]
name = "simple_ws_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "*"
pretty_env_logger = "0.4"
log = "0.4"
futures-util = "0.3.31"
